### PR TITLE
Membuat-Skema-Table-User-dan-migrasi-ke-database

### PR DESCRIPTION
**Pull request by arul14444**
bikin tabel user

### CODE REVIEW

**Comment by AufaAsmawy19551** [comment]
ada typo rul

**Comment by AufaAsmawy19551** [comment]
di file migration create user line 20

**Comment by arul14444** [comment]
udah ni

**Comment by AufaAsmawy19551** [comment]
ok

**Review by AufaAsmawy19551 — APPROVED** [review]
udah ok

**Pull request merged**
